-- AJUSTES PERSONALIZADOS


CREATE SCHEMA IF NOT EXISTS AGDBDDS02 DEFAULT CHARACTER SET latin1 ;
USE AGDBDDS02 ;

-- -----------------------------------------------------
-- Table AGDBDDS02.AGDC_CAT_APLICATIVO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS AGDBDDS02.AGDC_CAT_APLICATIVO (
  CVE_APLICATIVO INT(11) NOT NULL AUTO_INCREMENT,
  REF_NOMBRE_CORTO VARCHAR(50) NULL DEFAULT NULL,
  DES_APLICATIVO VARCHAR(300) NULL DEFAULT NULL,
  CVE_USUARIO_ALTA CHAR(20) NOT NULL,
  FEC_ALTA_REGISTRO TIMESTAMP(6) NOT NULL,
  CVE_USUARIO_MODIFICA CHAR(20) NULL DEFAULT NULL,
  FEC_MODIFICA_REGISTRO TIMESTAMP(6) NULL DEFAULT NULL,
  FEC_BAJA TIMESTAMP(6) NULL DEFAULT NULL,
  PRIMARY KEY (CVE_APLICATIVO));
  
---MIGRANDO DATOS

INSERT INTO AGDBDDS02.AGDC_CAT_APLICATIVO
	SELECT A.*, 'USR_CARGA_MANUAL',CURRENT_DATE,NULL,NULL,NULL
	FROM AGDBDDS01.AGDC_CAT_APLICATIVO A;


-- -----------------------------------------------------
-- Table AGDBDDS02.AGDC_CAT_DBMS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS AGDBDDS02.AGDC_CAT_DBMS (
  CVE_DBMS INT(11) NOT NULL AUTO_INCREMENT,
  DES_DBMS VARCHAR(200) NULL DEFAULT NULL,
  CVE_USUARIO_ALTA CHAR(20) NOT NULL,
  FEC_ALTA_REGISTRO TIMESTAMP(6) NOT NULL,
  CVE_USUARIO_MODIFICA CHAR(20) NULL DEFAULT NULL,
  FEC_MODIFICA_REGISTRO TIMESTAMP(6) NULL DEFAULT NULL,
  FEC_BAJA TIMESTAMP(6) NULL DEFAULT NULL,
  PRIMARY KEY (CVE_DBMS));

INSERT INTO AGDBDDS02.AGDC_CAT_DBMS
	SELECT A.*, 'USR_CARGA_MANUAL',CURRENT_DATE,NULL,NULL,NULL
	FROM AGDBDDS01.AGDC_CAT_DBMS A;
	
-- -----------------------------------------------------
-- Table AGDBDDS02.AGDT_CTL_USUARIO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS AGDBDDS02.AGDT_CTL_USUARIO (
  CVE_USUARIO CHAR(20) NOT NULL,
  PSW_USUARIO VARCHAR(512) NOT NULL,
  REF_NOMBRE_USUARIO VARCHAR(60) NULL DEFAULT NULL,
  REF_PATERNO_USUARIO VARCHAR(60) NULL DEFAULT NULL,
  REF_MATERNO_USUARIO VARCHAR(60) NULL DEFAULT NULL,
  REF_IS CHAR(10) NULL DEFAULT NULL,
  CVE_USUARIO_ALTA CHAR(20) NOT NULL,
  FEC_ALTA_REGISTRO TIMESTAMP(6) NOT NULL,
  CVE_USUARIO_MODIFICA CHAR(20) NULL DEFAULT NULL,
  FEC_MODIFICA_REGISTRO TIMESTAMP(6) NULL DEFAULT NULL,
  FEC_BAJA TIMESTAMP(6) NULL DEFAULT NULL,
  PRIMARY KEY (CVE_USUARIO));

INSERT INTO AGDBDDS02.AGDT_CTL_USUARIO
	SELECT A.CVE_USUARIO,
		A.PSW_USUARIO,
		A.REF_NOMBRE_USUARIO,
		A.REF_PATERNO_USUARIO,
		A.REF_MATERNO_USUARIO,
		A.REF_IS,
		'USR_CARGA_MANUAL',
		CURRENT_DATE,
		NULL,NULL,NULL
	FROM AGDBDDS01.AGDT_CTL_USUARIOS A;

-- -----------------------------------------------------
-- Table AGDBDDS02.AGDT_PCS_SERVIDOR
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS AGDBDDS02.AGDT_PCS_SERVIDOR (
  CVE_SERVIDOR INT(11) NOT NULL AUTO_INCREMENT,
  CVE_USUARIO CHAR(20) NULL DEFAULT NULL,
  REF_NOMBRE_SERVIDOR VARCHAR(100) NULL DEFAULT NULL,
  REF_AMBIENTE CHAR(4) NULL DEFAULT NULL,
  REF_IP CHAR(15) NULL DEFAULT NULL,
  REF_SISTEMA_OPERATIVO VARCHAR(30) NULL DEFAULT NULL,
  IND_SE_RESPALDA BOOLEAN NULL DEFAULT NULL,
  REF_SITE CHAR(5) NULL DEFAULT NULL,
  IND_SERVICIO_VITUALIZADO BOOLEAN NULL DEFAULT NULL,
  REF_VIRTUALIZADOR VARCHAR(100) NULL DEFAULT NULL,
  REF_LICENCIAMIENTO VARCHAR(200) NULL DEFAULT NULL,
  CVE_USUARIO_ALTA CHAR(20) NOT NULL,
  FEC_ALTA_REGISTRO TIMESTAMP(6) NOT NULL,
  CVE_USUARIO_MODIFICA CHAR(20) NULL DEFAULT NULL,
  FEC_MODIFICA_REGISTRO TIMESTAMP(6) NULL DEFAULT NULL,
  FEC_BAJA TIMESTAMP(6) NULL DEFAULT NULL,
  PRIMARY KEY (CVE_SERVIDOR),
  INDEX AGDCNS_FK_CAT_USR (CVE_USUARIO ASC) VISIBLE,
  CONSTRAINT AGDCNS_FK_CAT_USR0
    FOREIGN KEY (CVE_USUARIO)
    REFERENCES AGDBDDS02.AGDT_CTL_USUARIO (CVE_USUARIO));
--AL INTENTAR POBLAR LAS TABLAS SE DETACTARON INCONSISTENCIAS EN LOS DATOS, SE RPOCEDE A DAR ESTAS REMEDIACIONES
--SERVIDOR 172.16.164.45 APARECE 2 VECES, SE PROCEDE A DEJAR UN SOLO AMBIENTE  Y SE ACTUALIZA NOMBRE DEL SERVIDOR
DELETE FROM AGDBDDS01.AGDT_PCS_INVENTARIO_SERVIDORES
WHERE REF_IP='IP2';

UPDATE AGDBDDS01.AGDT_PCS_INVENTARIO_SERVIDORES
	SET REF_AMBIENTE='QA'
WHERE REF_IP='172.16.164.45';

UPDATE AGDBDDS01.AGDT_PCS_INVENTARIO_SERVIDORES
	SET REF_AMBIENTE='PROD'
WHERE REF_IP='10.100.8.74';

UPDATE AGDBDDS01.AGDT_PCS_INVENTARIO_SERVIDORES
	SET REF_AMBIENTE='QA'
WHERE REF_IP='10.100.6.57';

UPDATE AGDBDDS01.AGDT_PCS_INVENTARIO_SERVIDORES
	SET REF_AMBIENTE='QA'
WHERE REF_IP='10.100.8.87';

UPDATE AGDBDDS01.AGDT_PCS_INVENTARIO_SERVIDORES
	SET REF_AMBIENTE='QA'
WHERE REF_IP IN ('10.100.8.89','10.100.8.145');

UPDATE AGDBDDS01.AGDT_PCS_INVENTARIO_SERVIDORES
	SET REF_NOMBRE_SERVIDOR='cnvqabdlabo01',
		REF_SISTEMA_OPERATIVO='LINUX(el7uek.x86_64)'
WHERE REF_IP='10.100.8.91';

UPDATE AGDBDDS01.AGDT_PCS_INVENTARIO_SERVIDORES
	SET REF_NOMBRE_SERVIDOR='s5vqdbpssdp01',
		REF_SISTEMA_OPERATIVO='LINUX',
		CVE_USUARIO='raul.castro'
WHERE REF_IP='172.16.164.10';

UPDATE AGDBDDS01.AGDT_PCS_INVENTARIO_SERVIDORES
	SET REF_NOMBRE_SERVIDOR='s5vqdbpssdp01',
		REF_SISTEMA_OPERATIVO='LINUX',
		CVE_USUARIO='raul.castro'
WHERE REF_IP='10.100.8.76';

UPDATE AGDBDDS01.AGDT_PCS_INVENTARIO_SERVIDORES
	SET REF_VERSION_DBMS='10.5.4'
WHERE REF_IP='10.100.8.26';

UPDATE AGDBDDS01.AGDT_PCS_INVENTARIO_SERVIDORES
	SET REF_SISTEMA_OPERATIVO=TRIM(UPPER(REF_SISTEMA_OPERATIVO));

UPDATE AGDBDDS01.AGDT_PCS_INVENTARIO_SERVIDORES 
	SET REF_VERSION_DBMS='11 G Enterprice Release 11.2.0.40'
WHERE REF_IP='172.16.164.10';
--LAS VARIABLES PARA ENTRAR COMO SYS SON DIFERENTES EN 2 REGISTROS QUE SE REFIEREN A LA MISMA INSTANCIA DE BD

UPDATE AGDBDDS01.AGDT_PCS_INVENTARIO_SERVIDORES 
		SET REF_OBSERVACIOES='export ORACLE_HOME=/oracle/app/oracle/product/19.3.0/dbhome_1 export PATH=$PATH:$ORACLE_HOME/bin export ORACLE_SID=VCVDBDUAT sqlplus / as sysdba'
	WHERE CVE_INVENTARIO_SERVIDORES=112;

--REGISTRO DUPLICADO, POR ESO SE ELIMINA (IDS CON MISMA INFO 31,62)
DELETE FROM AGDBDDS01.AGDT_PCS_INVENTARIO_SERVIDORES WHERE CVE_INVENTARIO_SERVIDORES=31;

--USUARIO INCORRECTO DE SISTEMA OPERATIVO
UPDATE AGDBDDS01.AGDT_PCS_INVENTARIO_SERVIDORES 
		SET REF_SO_PASSWORD='Passw0rd'
	WHERE CVE_INVENTARIO_SERVIDORES=42;

INSERT INTO AGDBDDS02.AGDT_PCS_SERVIDOR (CVE_USUARIO,
  REF_NOMBRE_SERVIDOR,
  REF_AMBIENTE,
  REF_IP,
  REF_SISTEMA_OPERATIVO,
  IND_SE_RESPALDA,
  REF_SITE,
  CVE_USUARIO_ALTA,
  FEC_ALTA_REGISTRO)
	SELECT DISTINCT A.CVE_USUARIO,
		A.REF_NOMBRE_SERVIDOR,
		A.REF_AMBIENTE,
		A.REF_IP,
		A.REF_SISTEMA_OPERATIVO,
		A.IND_SE_RESPALDA,
		A.REF_SITE,
		'USR_CARGA_MANUAL',
		CURRENT_DATE
	FROM AGDBDDS01.AGDT_PCS_INVENTARIO_SERVIDORES A
	ORDER BY A.REF_IP;
	
-- -----------------------------------------------------
-- Table AGDBDDS02.AGDT_PCS_SERVIDOR_DBMS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS AGDBDDS02.AGDT_PCS_SERVIDOR_DBMS (
	CVE_SERVIDOR_DBMS INT(11) NOT NULL AUTO_INCREMENT,
	CVE_SERVIDOR INT(11) NOT NULL,
	CVE_APLICATIVO INT(11) NULL DEFAULT NULL,
	CVE_DBMS INT(11) NULL DEFAULT NULL,
	REF_RELEASE_DBMS VARCHAR(200) NULL DEFAULT NULL,
	REF_VERSION_DBMS VARCHAR(200) NULL DEFAULT NULL,
	REF_SID VARCHAR(30) NULL DEFAULT NULL,
	REF_PUERTO CHAR(7) NULL DEFAULT NULL,
	REF_OBSERVACIONES VARCHAR(300) NULL DEFAULT NULL,
	CVE_USUARIO_ALTA CHAR(20) NOT NULL,
	FEC_ALTA_REGISTRO TIMESTAMP(6) NOT NULL,
	CVE_USUARIO_MODIFICA CHAR(20) NULL DEFAULT NULL,
	FEC_MODIFICA_REGISTRO TIMESTAMP(6) NULL DEFAULT NULL,
	FEC_BAJA TIMESTAMP(6) NULL DEFAULT NULL,
PRIMARY KEY (CVE_SERVIDOR_DBMS),
INDEX FK_AGDT_PCS_SERVIDOR_DBMS_AGDT_PCS_SERVIDOR1_idx (CVE_SERVIDOR ASC) VISIBLE,
CONSTRAINT fk_AGDT_PCS_CREDENCIAL_AGDT_PCS_SERVIDOR1
	FOREIGN KEY (CVE_SERVIDOR)
	REFERENCES AGDBDDS02.AGDT_PCS_SERVIDOR (CVE_SERVIDOR),
INDEX AGDCNS_FK_CAT_APP (CVE_APLICATIVO ASC) VISIBLE,
  CONSTRAINT AGDCNS_FK_CAT_APP0
    FOREIGN KEY (CVE_APLICATIVO)
    REFERENCES AGDBDDS02.AGDC_CAT_APLICATIVO (CVE_APLICATIVO));
	
INSERT INTO AGDBDDS02.AGDT_PCS_SERVIDOR_DBMS
	(CVE_SERVIDOR, 
	CVE_APLICATIVO,
	CVE_DBMS,
	REF_VERSION_DBMS,
	REF_SID,
	REF_PUERTO,
	REF_OBSERVACIONES,
	CVE_USUARIO_ALTA,
	FEC_ALTA_REGISTRO)
SELECT DISTINCT 
	B.CVE_SERVIDOR,
	A.CVE_APLICATIVO,
	A.CVE_DBMS,
	A.REF_VERSION_DBMS,
	A.REF_SID,
	A.REF_PUERTO,
	A.REF_OBSERVACIOES,
	'USR_CARGA_MANUAL',
	CURRENT_DATE
FROM AGDBDDS01.AGDT_PCS_INVENTARIO_SERVIDORES A,
	AGDBDDS02.AGDT_PCS_SERVIDOR B
WHERE
	A.REF_IP=B.REF_IP
ORDER BY B.REF_IP;
	
-- -----------------------------------------------------
-- Table AGDBDDS02.AGDT_PCS_CREDENCIAL
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS AGDBDDS02.AGDT_PCS_SERVIDOR_CREDENCIAL (
	CVE_SERVIDOR_CREDENCIAL INT NOT NULL AUTO_INCREMENT,
	CVE_SERVIDOR INT(11) NOT NULL,
	REF_ESQUEMA VARCHAR(30) NULL DEFAULT NULL,
	REF_USUARIO VARCHAR(30) NULL DEFAULT NULL,
	REF_PASSWORD VARCHAR(30) NULL DEFAULT NULL,
	REF_TIPO_USUARIO VARCHAR(100) NULL DEFAULT NULL,
	CVE_USUARIO_ALTA CHAR(20) NOT NULL,
	FEC_ALTA_REGISTRO TIMESTAMP(6) NOT NULL,
	CVE_USUARIO_MODIFICA CHAR(20) NULL DEFAULT NULL,
	FEC_MODIFICA_REGISTRO TIMESTAMP(6) NULL DEFAULT NULL,
	FEC_BAJA TIMESTAMP(6) NULL DEFAULT NULL,
PRIMARY KEY (CVE_SERVIDOR_CREDENCIAL),
INDEX FK_AGDT_PCS_SERVIDOR_CREDENCIAL_1_idx (CVE_SERVIDOR ASC) VISIBLE,
CONSTRAINT fk_AGDT_PCS_CREDENCIAL_AGDT_PCS_SERVIDOR2
	FOREIGN KEY (CVE_SERVIDOR)
	REFERENCES AGDBDDS02.AGDT_PCS_SERVIDOR (CVE_SERVIDOR));

INSERT INTO AGDBDDS02.AGDT_PCS_SERVIDOR_CREDENCIAL
	(CVE_SERVIDOR,
	REF_ESQUEMA,
	REF_USUARIO,
	REF_PASSWORD,
	REF_TIPO_USUARIO,
	CVE_USUARIO_ALTA,
	FEC_ALTA_REGISTRO
	)
SELECT 
	B.CVE_SERVIDOR,
	A.REF_ESQUEMA,
	A.REF_BD_USUARIO,
	A.REF_BD_PASSWORD,
	A.REF_BD_USUARIO_TIPO,
	'USR_CARGA_MANUAL',
	CURRENT_DATE
FROM AGDBDDS01.AGDT_PCS_INVENTARIO_SERVIDORES A,
	AGDBDDS02.AGDT_PCS_SERVIDOR B
WHERE
	A.REF_IP=B.REF_IP
ORDER BY B.REF_IP;

INSERT INTO AGDBDDS02.AGDT_PCS_SERVIDOR_CREDENCIAL
	(CVE_SERVIDOR,
	REF_ESQUEMA,
	REF_USUARIO,
	REF_PASSWORD,
	REF_TIPO_USUARIO,
	CVE_USUARIO_ALTA,
	FEC_ALTA_REGISTRO
	)
SELECT DISTINCT
	B.CVE_SERVIDOR,
	null,
	A.REF_SO_USUARIO,
	A.REF_SO_PASSWORD,
	'USUARIO DE SISTEMA OPERATIVO',
	'USR_CARGA_MANUAL',
	CURRENT_DATE
FROM AGDBDDS01.AGDT_PCS_INVENTARIO_SERVIDORES A,
	AGDBDDS02.AGDT_PCS_SERVIDOR B
WHERE
	A.REF_IP=B.REF_IP
	AND A.REF_SO_PASSWORD IS NOT NULL
	AND TRIM(A.REF_SO_PASSWORD)!=''
ORDER BY B.REF_IP;
	
-- -----------------------------------------------------
-- Table AGDBDDS02.AGDT_PCS_HIST_SERVIDOR
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS AGDBDDS02.AGDT_PCS_HIST_SERVIDOR (
  CVE_HIST_SERVIDOR INT NOT NULL AUTO_INCREMENT,
  CVE_SERVIDOR INT(11) NOT NULL,
  CVE_USUARIO CHAR(20) NULL DEFAULT NULL,
  REF_NOMBRE_SERVIDOR VARCHAR(100) NULL DEFAULT NULL,
  REF_AMBIENTE CHAR(4) NULL DEFAULT NULL,
  REF_IP CHAR(15) NULL DEFAULT NULL,
  REF_SISTEMA_OPERATIVO VARCHAR(30) NULL DEFAULT NULL,
  IND_SE_RESPALDA BOOLEAN NULL DEFAULT NULL,
  REF_SITE CHAR(5) NULL DEFAULT NULL,
  IND_SERVICIO_VITUALIZADO BOOLEAN NULL DEFAULT NULL,
  REF_VIRTUALIZADOR VARCHAR(100) NULL DEFAULT NULL,
  REF_LICENCIAMIENTO VARCHAR(200) NULL DEFAULT NULL,
  CVE_USUARIO_ALTA CHAR(20) NOT NULL,
  FEC_ALTA_REGISTRO TIMESTAMP(6) NOT NULL,
  CVE_USUARIO_MODIFICA CHAR(20) NULL DEFAULT NULL,
  FEC_MODIFICA_REGISTRO TIMESTAMP(6) NULL DEFAULT NULL,
  FEC_BAJA TIMESTAMP(6) NULL DEFAULT NULL,
  PRIMARY KEY (CVE_HIST_SERVIDOR));


-- -----------------------------------------------------
-- Table AGDBDDS02.AGDT_PCS_HIST_SERVIDOR_DBMS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS AGDBDDS02.AGDT_PCS_HIST_SERVIDOR_DBMS (
	CVE_HIST_SERVIDOR_DBMS INT NOT NULL AUTO_INCREMENT,
	CVE_SERVIDOR_DBMS INT(11) NOT NULL,
	CVE_SERVIDOR INT(11) NOT NULL,
	CVE_APLICATIVO INT(11) NULL DEFAULT NULL,
	CVE_DBMS INT(11) NULL DEFAULT NULL,
	REF_RELEASE_DBMS VARCHAR(200) NULL DEFAULT NULL,
	REF_VERSION_DBMS VARCHAR(200) NULL DEFAULT NULL,
	REF_SID VARCHAR(30) NULL DEFAULT NULL,
	REF_PUERTO CHAR(7) NULL DEFAULT NULL,
	REF_OBSERVACIONES VARCHAR(300) NULL DEFAULT NULL,
	CVE_USUARIO_ALTA CHAR(20) NOT NULL,
	FEC_ALTA_REGISTRO TIMESTAMP(6) NOT NULL,
	CVE_USUARIO_MODIFICA CHAR(20) NULL DEFAULT NULL,
	FEC_MODIFICA_REGISTRO TIMESTAMP(6) NULL DEFAULT NULL,
	FEC_BAJA TIMESTAMP(6) NULL DEFAULT NULL,
PRIMARY KEY (CVE_HIST_SERVIDOR_DBMS));
	
	
-- -----------------------------------------------------
-- Table AGDBDDS02.AGDT_PCS_SERVIDOR_CREDENCIAL
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS AGDBDDS02.AGDT_PCS_SERVIDOR_CREDENCIAL (
	CVE_HIST_SERVIDOR_CREDENCIAL INT NOT NULL AUTO_INCREMENT,
	CVE_SERVIDOR_CREDENCIAL INT NOT NULL,
	CVE_SERVIDOR INT(11) NOT NULL,
	REF_ESQUEMA VARCHAR(30) NULL DEFAULT NULL,
	REF_USUARIO VARCHAR(30) NULL DEFAULT NULL,
	REF_PASSWORD VARCHAR(30) NULL DEFAULT NULL,
	REF_TIPO_USUARIO VARCHAR(100) NULL DEFAULT NULL,
	CVE_USUARIO_ALTA CHAR(20) NOT NULL,
	FEC_ALTA_REGISTRO TIMESTAMP(6) NOT NULL,
	CVE_USUARIO_MODIFICA CHAR(20) NULL DEFAULT NULL,
	FEC_MODIFICA_REGISTRO TIMESTAMP(6) NULL DEFAULT NULL,
	FEC_BAJA TIMESTAMP(6) NULL DEFAULT NULL,
PRIMARY KEY (CVE_HIST_SERVIDOR_CREDENCIAL));



--CONSULTAS

SELECT * FROM AGDBDDS02.AGDT_PCS_SERVIDOR;
SELECT * FROM AGDBDDS02.AGDT_PCS_SERVIDOR_DBMS;
SELECT * FROM AGDBDDS02.AGDT_PCS_SERVIDOR_CREDENCIAL;