-- USE 
--PARA ENCRIPTAR EL PASSWORD ALMACENADO:
--cve: IMSS_AGD_@073
select cve_usuario, AES_enCRYPT(PSW_usuario,'IMSS_AGD_@073') from agdt_ctl_usuarios;

UPDATE AGDT_CTL_USUARIO
	SET PSW_USUARIO=AES_ENCRYPT(PSW_USUARIO,'IMSS_AGD_@073');
	
SELECT * 
FROM AGDT_CTL_USUARIOS 
WHERE CVE_USUARIO='erick.herrera'
	AND PSW_USUARIO='Muneca250';